# Generated by Django 5.0.7 on 2024-08-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trailerrentalrequest_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailerrentalrequest',
            name='trailer_details',
            field=models.CharField(max_length=500),
        ),
    ]
